#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prikazRacuna
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pregledRacuna")]
	public partial class pregledRacunaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFirma(Firma instance);
    partial void UpdateFirma(Firma instance);
    partial void DeleteFirma(Firma instance);
    partial void InsertRacun(Racun instance);
    partial void UpdateRacun(Racun instance);
    partial void DeleteRacun(Racun instance);
    #endregion
		
		public pregledRacunaDataContext() : 
				base(global::prikazRacuna.Properties.Settings.Default.pregledRacunaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public pregledRacunaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pregledRacunaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pregledRacunaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public pregledRacunaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Firma> Firmas
		{
			get
			{
				return this.GetTable<Firma>();
			}
		}
		
		public System.Data.Linq.Table<Racun> Racuns
		{
			get
			{
				return this.GetTable<Racun>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Firma")]
	public partial class Firma : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDPIB;
		
		private string _MB;
		
		private string _Naziv;
		
		private string _Sediste;
		
		private string _TR;
		
		private EntitySet<Racun> _Racuns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPIBChanging(string value);
    partial void OnIDPIBChanged();
    partial void OnMBChanging(string value);
    partial void OnMBChanged();
    partial void OnNazivChanging(string value);
    partial void OnNazivChanged();
    partial void OnSedisteChanging(string value);
    partial void OnSedisteChanged();
    partial void OnTRChanging(string value);
    partial void OnTRChanged();
    #endregion
		
		public Firma()
		{
			this._Racuns = new EntitySet<Racun>(new Action<Racun>(this.attach_Racuns), new Action<Racun>(this.detach_Racuns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPIB", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDPIB
		{
			get
			{
				return this._IDPIB;
			}
			set
			{
				if ((this._IDPIB != value))
				{
					this.OnIDPIBChanging(value);
					this.SendPropertyChanging();
					this._IDPIB = value;
					this.SendPropertyChanged("IDPIB");
					this.OnIDPIBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MB", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MB
		{
			get
			{
				return this._MB;
			}
			set
			{
				if ((this._MB != value))
				{
					this.OnMBChanging(value);
					this.SendPropertyChanging();
					this._MB = value;
					this.SendPropertyChanged("MB");
					this.OnMBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziv", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Naziv
		{
			get
			{
				return this._Naziv;
			}
			set
			{
				if ((this._Naziv != value))
				{
					this.OnNazivChanging(value);
					this.SendPropertyChanging();
					this._Naziv = value;
					this.SendPropertyChanged("Naziv");
					this.OnNazivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sediste", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Sediste
		{
			get
			{
				return this._Sediste;
			}
			set
			{
				if ((this._Sediste != value))
				{
					this.OnSedisteChanging(value);
					this.SendPropertyChanging();
					this._Sediste = value;
					this.SendPropertyChanged("Sediste");
					this.OnSedisteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TR", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TR
		{
			get
			{
				return this._TR;
			}
			set
			{
				if ((this._TR != value))
				{
					this.OnTRChanging(value);
					this.SendPropertyChanging();
					this._TR = value;
					this.SendPropertyChanged("TR");
					this.OnTRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firma_Racun", Storage="_Racuns", ThisKey="IDPIB", OtherKey="FK_PIB")]
		public EntitySet<Racun> Racuns
		{
			get
			{
				return this._Racuns;
			}
			set
			{
				this._Racuns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Racuns(Racun entity)
		{
			this.SendPropertyChanging();
			entity.Firma = this;
		}
		
		private void detach_Racuns(Racun entity)
		{
			this.SendPropertyChanging();
			entity.Firma = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Racun")]
	public partial class Racun : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FK_PIB;
		
		private string _BR_RAC;
		
		private System.DateTime _Datum;
		
		private System.Nullable<double> _Duguje;
		
		private System.Nullable<double> _Potrazuje;
		
		private EntityRef<Firma> _Firma;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFK_PIBChanging(string value);
    partial void OnFK_PIBChanged();
    partial void OnBR_RACChanging(string value);
    partial void OnBR_RACChanged();
    partial void OnDatumChanging(System.DateTime value);
    partial void OnDatumChanged();
    partial void OnDugujeChanging(System.Nullable<double> value);
    partial void OnDugujeChanged();
    partial void OnPotrazujeChanging(System.Nullable<double> value);
    partial void OnPotrazujeChanged();
    #endregion
		
		public Racun()
		{
			this._Firma = default(EntityRef<Firma>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_PIB", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FK_PIB
		{
			get
			{
				return this._FK_PIB;
			}
			set
			{
				if ((this._FK_PIB != value))
				{
					if (this._Firma.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_PIBChanging(value);
					this.SendPropertyChanging();
					this._FK_PIB = value;
					this.SendPropertyChanged("FK_PIB");
					this.OnFK_PIBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BR_RAC", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BR_RAC
		{
			get
			{
				return this._BR_RAC;
			}
			set
			{
				if ((this._BR_RAC != value))
				{
					this.OnBR_RACChanging(value);
					this.SendPropertyChanging();
					this._BR_RAC = value;
					this.SendPropertyChanged("BR_RAC");
					this.OnBR_RACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="DateTime NOT NULL")]
		public System.DateTime Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this.OnDatumChanging(value);
					this.SendPropertyChanging();
					this._Datum = value;
					this.SendPropertyChanged("Datum");
					this.OnDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duguje", DbType="Float")]
		public System.Nullable<double> Duguje
		{
			get
			{
				return this._Duguje;
			}
			set
			{
				if ((this._Duguje != value))
				{
					this.OnDugujeChanging(value);
					this.SendPropertyChanging();
					this._Duguje = value;
					this.SendPropertyChanged("Duguje");
					this.OnDugujeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Potrazuje", DbType="Float")]
		public System.Nullable<double> Potrazuje
		{
			get
			{
				return this._Potrazuje;
			}
			set
			{
				if ((this._Potrazuje != value))
				{
					this.OnPotrazujeChanging(value);
					this.SendPropertyChanging();
					this._Potrazuje = value;
					this.SendPropertyChanged("Potrazuje");
					this.OnPotrazujeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Firma_Racun", Storage="_Firma", ThisKey="FK_PIB", OtherKey="IDPIB", IsForeignKey=true)]
		public Firma Firma
		{
			get
			{
				return this._Firma.Entity;
			}
			set
			{
				Firma previousValue = this._Firma.Entity;
				if (((previousValue != value) 
							|| (this._Firma.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Firma.Entity = null;
						previousValue.Racuns.Remove(this);
					}
					this._Firma.Entity = value;
					if ((value != null))
					{
						value.Racuns.Add(this);
						this._FK_PIB = value.IDPIB;
					}
					else
					{
						this._FK_PIB = default(string);
					}
					this.SendPropertyChanged("Firma");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
